[uwsgi]
strict = true
die-on-term = true
uid = fastuser
gid = fastuser
chdir = /var/www/fastuser/data/www/stroygrouppik.ru
wsgi-file = wsgi.py
venv = /var/www/fastuser/data/www/stroygrouppik.ru/venv
socket = 127.0.0.1:3000
callable = app
